### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#106] opened 2024-11-15 17:04 UTC
Is there any possibility to fix that if there are too many inputs in programble dual input hatch it starts to alternate recipes instead of loading at most 1 cache?

Video
https://imgur.com/Uf6bpWG

**Comment by reobf** [comment] 2024-11-15 17:13
Well this is how AE works, iterate all patterns and try to push **one** of each type.
Then iterate again until co-processors are exhausted.
That's to say, AE tends to push more types of pattens rather than single pattern for many times.
Yup that sucks

**Comment by reobf** [comment] 2024-11-15 17:14
You might grab a Crafting Dumper(no recipe) from NEI.
That's an experimental block.

**Comment by reobf** [comment] 2024-11-15 17:14
You might grab a Crafting Dumper(no recipe) from nei.
That's an experimental block.

**Comment by reobf** [comment] 2024-11-15 17:16
Add it to your Crafting CPU, and it will retry several times immediately after one pattern pushed successifully.
Rather than try another pattern

**Comment by reobf** [comment] 2024-11-15 17:17
If you are talking about some 'vanilla' ways to solve it, the answer might be NO.

**Comment by evgengoldwar** [comment] 2024-11-15 17:18
> Add it to your Crafting CPU, and it will retry several times immediately after one pattern pushed successifully. Rather than try another pattern

![image](https://github.com/user-attachments/assets/6512b742-73c7-40bb-940b-96d38b162089)

this ?

**Comment by reobf** [comment] 2024-11-15 17:19
yes

**Comment by reobf** [comment] 2024-11-15 17:20
And I add a one sec delay to recipe auto-unlock.
So the 'strange situation' in WAILA is actually normal(or a glitch).

**Comment by reobf** [comment] 2024-11-16 07:14
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p26-beta
Previously Crafting Dumper will retry pushing pattern even if it fails for workbench pattern.
If you use max tier Crafting Dumper it will freeze ur game(it will try int.max times).
Plz update it if you wan't to use Crafting Dumper.

**Comment by evgengoldwar** [comment] 2024-11-16 18:31
> https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p26-beta Sorry the experimental block has a bug Previously Crafting Dumper will retry pushing pattern even if it fails for workbench pattern. If you use max tier Crafting Dumper it will freeze ur game(it will try int.max times). Plz update it if you wan't to use Crafting Dumper.

![image](https://github.com/user-attachments/assets/3bef8ab1-8b92-41e5-9907-8d5162380ef8)

Last version mods

It could do that, but it doesn't.

**Comment by reobf** [comment] 2024-11-16 19:18
[programmablehatches-0.0.19p27-GTNH270.zip](https://github.com/user-attachments/files/17787705/programmablehatches-0.0.19p27-GTNH270.zip)
sorry my mistake, should fix it this time... 
try this one, no not unzip rename to .jar

**Comment by reobf** [comment] 2024-11-17 09:09
There were 2 different bugs about this block
1.  failing to push patterns into Mocular Assembler does not stop the retry ,thus causing huge lag or even freeze the game(fixed in p26)
2.  Stucked in 'scheduled'. this is caused by dumper only check whether should push patterns ,depends **only on** if material is sufficient. Not taking number of tasks into consideration.
So most copper ingots are made into wire, causing bolt lacking materials. Then stuck in 'scheduled'.

The file above should fix the 2nd bug.

**Closed** 2024-11-21 17:26 UTC
