### ISSUE TITLE
Add new stocking for assembling line?

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#75] opened 2024-10-06 15:25 UTC
Maybe add a UV+ stocking for the assembling line, which will take the necessary items from the subnet itself, which would make it easier to build new assembling line without communication.

**Comment by TimberDimber** [comment] 2024-10-06 15:27
I suggest trying something a little different:
Add a special stocker for items/liquids, inside which you can specify the corresponding priority/channel and which will take items/liquids according to it. This would allow you to build an ass-line by placing only 20 stockers and copying their settings by data orb, as it became possible in 2.7.

**Comment by reobf** [comment] 2024-10-08 13:02
> Maybe add a UV+ stocking for the assembling line, which will take the necessary items from the subnet itself, which would make it easier to build new assembling line without communication.

'take necessary items' 'without communication', that sounds a little technically impossible...
What you're talking about is more like an assembler doing Assline recipe.

**Comment by reobf** [comment] 2024-10-08 13:06
> I suggest trying something a little different: Add a special stocker for items/liquids, inside which you can specify the corresponding priority/channel and which will take items/liquids according to it. This would allow you to build an ass-line by placing only 20 stockers and copying their settings by data orb, as it became possible in 2.7.

Good idea!
Too bad dataorb support should be manually implemented, or else dataorb simply skip it.... 
I'll implement this first.

**Comment by TimberDimber** [comment] 2024-10-08 21:26
EvgenWarGold also asked whether it's possible to make all your dual inputs/slaves work similarly to how it was done with the original Stockings :  [as shown here](https://discord.com/channels/181078474394566657/295669878222880769/1266118249318187088)
Essentially, buss triggered instantly when an item enters the input, notifying the mech to start operating.

**Comment by reobf** [comment] 2024-10-09 01:01
> EvgenWarGold also asked whether it's possible to make all your dual inputs/slaves work similarly to how it was done with the original Stockings : [as shown here](https://discord.com/channels/181078474394566657/295669878222880769/1266118249318187088) Essentially, buss triggered instantly when an item enters the input, notifying the mech to start operating.

Actually it's already done. But only for the 'Buffered' versions and Slaves linked to those versions.
The Buffered Dual Hatch will notify the multi **when it detects and transfers** items/fluid into its buffer.
The Non-buffered Dual Hatch cannot do this, for the same reason regular Input Bus can't.

**Comment by TimberDimber** [comment] 2024-10-10 12:58
@reobf It seems that Priority Filtering Stocking Input Bus does not save ntb. When you restart, all priorities set in them are reset. Otherwise, everything works fine, especially in conjunction with decoy stocking.

However, today I found another bug: Restricted Stocking seems to ignore any settings set in it.
![image](https://github.com/user-attachments/assets/060a74e5-0f39-4868-b3b1-e6e83ac5191a)
![image](https://github.com/user-attachments/assets/f8a8bece-58a5-476b-80d6-23e24fc672b9)
![image](https://github.com/user-attachments/assets/66ef7fb6-0e9f-42e2-ad15-71296a44f37e)
![image](https://github.com/user-attachments/assets/98ef92e0-f352-4aad-a76c-b08493d2f63b)
As shown in the screenshots - there is less salt in the network than set in it, but the electrolyzer starts processing and does this until there is 0 left and turns on every time there is an opportunity to process.

**Comment by TimberDimber** [comment] 2024-10-10 13:15
Hatch work as must, but not item one

**Comment by reobf** [comment] 2024-10-10 16:05
Fixed
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p9-beta

**Comment by TimberDimber** [comment] 2024-10-10 16:06
Both of them?

**Comment by TimberDimber** [comment] 2024-10-10 16:07
> Fixed @TimberDimber https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p9-beta

'll check and let you know

**Comment by TimberDimber** [comment] 2024-10-10 16:10
> Fixed @TimberDimber https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p9-beta

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: gregtech/api/metatileentity/BaseMetaTileEntity
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: gregtech/api/metatileentity/BaseMetaTileEntity

**Comment by TimberDimber** [comment] 2024-10-10 16:10
Looks like it for 2.6.1?

**Comment by reobf** [comment] 2024-10-10 16:19
you are using mod with 'gtnh270'suffix on270-beta-1 server
right?

**Comment by TimberDimber** [comment] 2024-10-10 16:19
Yep

**Comment by TimberDimber** [comment] 2024-10-10 16:24
oh, sorry, i miss

**Comment by TimberDimber** [comment] 2024-10-10 16:26
Every time you make two release 270 beta and usual beta. Now I just miss it merged 😅

**Comment by reobf** [comment] 2024-10-10 16:29
Well because the 270beta ver is quite unstable, it's complied with 261 deps and then simply replaces java ref.
Someone tell me its not necessary to do that... so I merges them.

**Comment by TimberDimber** [comment] 2024-10-10 16:39
> Fixed @TimberDimber https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p9-beta

Okay, Priority Stocking works great. But there is one small omission: when you build it, it displays priority "1" by default - but it does not see the Bus with this priority and you can only set it back to 1 by changing it to any other and only then returning it to 1

**Comment by TimberDimber** [comment] 2024-10-10 16:41
Restricted fixed and fork as must. Tnx.

**Comment by TimberDimber** [comment] 2024-10-10 16:47
'll check it later. At the moment everything is working perfectly.

**Comment by TimberDimber** [comment] 2024-10-10 16:52
@evgengoldwar asked me next:
_Offer him a double AE output on, say, zpm-uv and a little further wireless the same_
How do you look at this?

**Comment by reobf** [comment] 2024-10-10 17:25
Dual ME output is not likely due to GT5 code limit
Even if done with Mixin or Coremod，support it on differet multis will be a torture. And its sure to break voiding mode rules.
About Wireless... ae2stuff is enough？

**Comment by TimberDimber** [comment] 2024-10-19 13:23
@reobf Is it possible to add usability Priority Card for Priority Stocking?

**Comment by reobf** [comment] 2024-10-19 13:39
> @reobf Is it possible to add usability Priority Card for Priority Stocking?

Such ‘priority’ is not regular ME Storage Priority, have to add it manually.
Will add it in the next release.

**Comment by reobf** [comment] 2024-10-19 15:55
> @reobf Is it possible to add usability Priority Card for Priority Stocking?

https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p14-beta
done

**Comment by evgengoldwar** [comment] 2024-10-26 10:08
> > @reobf Is it possible to add usability Priority Card for Priority Stocking?
> 
> https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p14-beta done

Couldn't Decoy Stocking add a recipe update when items are hit otherwise they take a very long time to turn on (

**Comment by evgengoldwar** [comment] 2024-10-26 10:09
And also is it possible to add ME Super Chest ability to take in a desired item from the whole ME like IO port ?

**Comment by reobf** [comment] 2024-10-26 10:44
> > > @reobf Is it possible to add usability Priority Card for Priority Stocking?
> > 
> > 
> > https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p14-beta done
> 
> Couldn't Decoy Stocking add a recipe update when items are hit otherwise they take a very long time to turn on (

I didn't override the expidit check code, so it should work the same as normal Advanced Stocking, are you sure it's not working?
Or it might be caused by default 100 ticks interval of auto pull.

**Comment by reobf** [comment] 2024-10-26 10:51
> And also is it possible to add ME Super Chest ability to take in a desired item from the whole ME like IO port ?

1.'desired' is hard to define.
2.Do you mean high priority of accepting specific type of item when item is injected into current ME Storage,
or 
gathering specific type of item from current ME Storage that is already stored (for example in ME Drive)?

**Comment by TimberDimber** [comment] 2024-10-26 12:04
> > And also is it possible to add ME Super Chest ability to take in a desired item from the whole ME like IO port ?
> 
> 
> 'desired' is hard to define. Like if it satisfies one Assline recipe?
> 
> 
> Do you mean high priority of accepting specific type of item when item is injected into current ME Storage(for example via IO Port you mentioned or import bus), or gathering specific type of item from current ME Storage that is already stored (for example in ME Drive)?
> 
> If the former, use priority or sticky mode. if the later, it's not likely due to AE design.

He mean next: add there button for push in/push out all items from/in ME. As example: chest bind for stone, in ME we have 1kkk stone. Push button and all stone from ME come in chest. So like I/O port, but without moving cell or use buses. And the reverse is similar - push all from chest to ME.

**Comment by TimberDimber** [comment] 2024-10-26 12:18
And, if it's not too difficult and annoying, can you describe the use case for Item/Fluid Proxy. It's looks like replacement for storage bus for subnet, or there are something more?

**Comment by reobf** [comment] 2024-10-26 12:35
> And, if it's not too difficult and annoying, can you describe the use case for Item/Fluid Proxy. It's looks like replacement for storage bus for subnet, or there are something more?

The problem is this feature has to scan every Storage in current Network frequently(because the normal ME Storage access does not exclude the ME Chest itself).
Just imagine two  ME Chests trying to pushing items into each other.

**Comment by reobf** [comment] 2024-10-26 12:42
Config in Item/Fluid Storage Bus provides only WRITING filter.
Config in Item/Fluid Proxy provides READING filter.

Normally if want subnet to only read some types of item, you have to mark items in ME Interface.
But the subnet can only read up to 64 tiems and those 64 items are not in the host net.
Replace the ME Interface with Proxy and mark items ，then you can read all item you marked in host net.

**Comment by TimberDimber** [comment] 2024-10-26 12:53
> Config in Item/Fluid Storage Bus provides only WRITING filter. Config in Item/Fluid Proxy provides READING filter.

I didn't quite understand. Let's say I have the following structure:
![image](https://github.com/user-attachments/assets/4c52feb5-6e8c-4d2a-bdb4-d4aaa7a9af99)

On the left is the interface that provides access to the main network, on the right is the storage bus, in which I specify which items it will see (if don't anything - it will see everything)
![image](https://github.com/user-attachments/assets/0711db0b-fbea-4856-b3a4-b1d3aac0d850)
![image](https://github.com/user-attachments/assets/000c29aa-a284-4177-80c2-eed38a9f35e8)

How will using a proxy be different instead of an interface?

**Comment by reobf** [comment] 2024-10-26 12:56
![2024-10-26_20 52 56](https://github.com/user-attachments/assets/b55ff06f-c4da-4ce3-8301-c220aa2b09ef)
![2024-10-26_20 53 00](https://github.com/user-attachments/assets/0731d939-4ea0-4c7d-bb64-15c6a29e15c1)
![2024-10-26_20 53 03](https://github.com/user-attachments/assets/d9415069-0229-40eb-a764-cc61aefd84e5)
![2024-10-26_20 53 06](https://github.com/user-attachments/assets/b478c3b7-9786-4361-ab3b-8e2512f3bfee)

**Comment by reobf** [comment] 2024-10-26 12:59
Well that will not specify what you see, but what the storage bus can put into the target.
not sure... it works this way in 2.6.1 
I will check in 270

**Comment by TimberDimber** [comment] 2024-10-26 12:59
![image](https://github.com/user-attachments/assets/eda2d7aa-7a6c-4ead-9003-a7254662988f)
![image](https://github.com/user-attachments/assets/96ca1dce-0d67-41f2-96f8-777a472629bd)
![image](https://github.com/user-attachments/assets/b48400b9-3164-419f-af13-7e25c3a39e26)
![image](https://github.com/user-attachments/assets/c11f5ba1-02ef-4543-ae6a-b531439ed67c)

**Comment by TimberDimber** [comment] 2024-10-26 12:59
> Well that will not specify what you see, but what the storage bus can put into the target. not sure... it works this way in 2.6.1 I will check in 270

oh... yes. it's 270 feature

**Comment by TimberDimber** [comment] 2024-10-26 13:01
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/553

This one

**Comment by reobf** [comment] 2024-10-26 13:08
Good PR.The old behaviour of Storage Bus is weird.

**Comment by TimberDimber** [comment] 2024-10-26 13:09
So, Proxy do exactly same?

**Comment by reobf** [comment] 2024-10-26 13:09
exactly

**Closed** 2024-11-15 16:58 UTC
